# Generated by Django 4.0 on 2021-12-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=50, null=True)),
                ('categorydescription', models.CharField(blank=True, db_column='categoryDescription', max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('countyname', models.CharField(db_column='countyName', max_length=30, primary_key=True, serialize=False)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'counties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('patientid', models.CharField(db_column='patientID', max_length=30, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('facultyid', models.CharField(db_column='facultyID', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'professors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentid', models.CharField(db_column='studentID', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
